# Generated by Django 5.2.8 on 2025-11-06 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_interaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinput',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.interactionsession'),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.userinput'),
        ),
    ]
