# Generated by Django 5.2.8 on 2025-11-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='user_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='user_interaction.userinput'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='user_interaction.interactionsession'),
        ),
    ]
