# Generated by Django 5.2.8 on 2025-11-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('user_interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ai_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.airesponse'),
        ),
    ]
