# Generated by Django 5.2.8 on 2025-11-06 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalnotice',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_notices', to='decision_reports.decisionreport'),
        ),
        migrations.AlterField(
            model_name='decisionreport',
            name='report_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
