# Generated by Django 5.2.8 on 2025-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('model_parameters', models.JSONField(blank=True, default=dict)),
                ('accuracy', models.FloatField(default=0.0)),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('content', 'Content'), ('interaction', 'Interaction'), ('learning', 'Learning')], max_length=20)),
                ('content', models.TextField()),
                ('confidence', models.FloatField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
