# Generated by Django 5.0.6 on 2026-02-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(unique=True)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords to match user input"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Question Categories",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("faq", "FAQ"),
                            ("tutorial", "Tutorial"),
                            ("documentation", "Documentation"),
                            ("article", "Article"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passage_text", models.TextField()),
                ("passage_number", models.IntegerField()),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Extracted or manual keywords"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Which model generated embedding",
                        max_length=100,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True, help_text="Last matched similarity score", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="recommendations.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "passage_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("relevance_score", models.FloatField(default=0.0)),
                (
                    "was_relevant",
                    models.BooleanField(
                        blank=True, help_text="User feedback on relevance", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommendations.document",
                    ),
                ),
                (
                    "matched_passage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommendations.documentpassage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="Explanation for this answer"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.8, help_text="Confidence level 0-1"),
                ),
                (
                    "use_openai",
                    models.BooleanField(
                        default=False, help_text="Generate this answer using OpenAI"
                    ),
                ),
                (
                    "prompt_override",
                    models.TextField(blank=True, help_text="Custom prompt for OpenAI"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="recommendations.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("ai_response", models.TextField()),
                ("emotional_state", models.CharField(blank=True, max_length=50)),
                ("confidence", models.FloatField(default=0.7)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback_text", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("fallback", "Fallback"),
                            ("stored", "Stored Answer"),
                            ("document", "Document Based"),
                        ],
                        default="fallback",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommendations.answer",
                    ),
                ),
                (
                    "matched_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommendations.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="recommendations.questioncategory",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpassage",
            index=models.Index(
                fields=["document", "is_active"], name="recommendat_documen_9f1b49_idx"
            ),
        ),
    ]
